[2024-06-17T12:00:26.514+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-17T12:00:26.636+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.load_process.load_shippers manual__2024-06-17T11:54:58.411739+00:00 [queued]>
[2024-06-17T12:00:26.689+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.load_process.load_shippers manual__2024-06-17T11:54:58.411739+00:00 [queued]>
[2024-06-17T12:00:26.692+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-17T12:00:26.778+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): load_process.load_shippers> on 2024-06-17 11:54:58.411739+00:00
[2024-06-17T12:00:26.795+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2366) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-17T12:00:26.796+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'load_process.load_shippers', 'manual__2024-06-17T11:54:58.411739+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpskspgr5j']
[2024-06-17T12:00:26.805+0000] {standard_task_runner.py:91} INFO - Job 267: Subtask load_process.load_shippers
[2024-06-17T12:00:26.803+0000] {standard_task_runner.py:63} INFO - Started process 2401 to run task
[2024-06-17T12:00:26.883+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-17T12:00:27.137+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.load_process.load_shippers manual__2024-06-17T11:54:58.411739+00:00 [running]> on host airflow-scheduler
[2024-06-17T12:00:27.698+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='load_process.load_shippers' AIRFLOW_CTX_EXECUTION_DATE='2024-06-17T11:54:58.411739+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-17T11:54:58.411739+00:00'
[2024-06-17T12:00:27.704+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-17T12:00:27.710+0000] {connection.py:399} INFO - Snowflake Connector for Python Version: 3.10.1, Python Version: 3.12.4, Platform: Linux-5.15.133.1-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2024-06-17T12:00:27.713+0000] {connection.py:1249} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T12:00:27.837+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T12:00:28.360+0000] {logging_mixin.py:188} INFO - Nama kolom di DataFrame: Index(['territoryID', 'territoryDescription', 'regionID'], dtype='object')
[2024-06-17T12:00:28.756+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T12:00:29.416+0000] {ssl_wrap_socket.py:100} INFO - THIS CONNECTION IS IN INSECURE MODE. IT MEANS THE CERTIFICATE WILL BE VALIDATED BUT THE CERTIFICATE REVOCATION STATUS WILL NOT BE CHECKED.
[2024-06-17T12:00:31.791+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T12:00:32.712+0000] {cursor.py:1149} INFO - Number of results in first chunk: 3
[2024-06-17T12:00:33.090+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T12:00:33.523+0000] {cursor.py:1149} INFO - Number of results in first chunk: 1
[2024-06-17T12:00:33.925+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-17T12:00:33.927+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/elt.py", line 67, in load
    load_func(df=df, table_names=table)
  File "/local_module/loaders.py", line 34, in load_func
    write_pandas(
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/pandas_tools.py", line 438, in write_pandas
    copy_results = cursor.execute(copy_into_sql, _is_internal=True).fetchall()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1080, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.12/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01b511b0-0000-8bcc-0000-ec9500046ac2: SQL compilation error: error line 1 at position 81
invalid identifier 'TERRITORYID'
[2024-06-17T12:00:33.972+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_products to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:33.973+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:33.994+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_customers to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:33.995+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:34.025+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_employee_territories to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:34.026+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:34.049+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_orders to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:34.050+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:34.089+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_suppliers to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:34.091+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:34.126+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_territories to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:34.127+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:34.183+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_order_details to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:34.190+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:34.220+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_categories to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:34.222+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:34.291+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_employees to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:34.292+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:34.336+0000] {taskinstance.py:222} INFO - Forcing task load_process.load_regions to fail due to dag's `fail_stop` setting
[2024-06-17T12:00:34.341+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-17T12:00:34.382+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ELT-PROJECT, task_id=load_process.load_shippers, run_id=manual__2024-06-17T11:54:58.411739+00:00, execution_date=20240617T115458, start_date=20240617T120026, end_date=20240617T120033
[2024-06-17T12:00:34.450+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 267 for task load_process.load_shippers (000904 (42000): 01b511b0-0000-8bcc-0000-ec9500046ac2: SQL compilation error: error line 1 at position 81
invalid identifier 'TERRITORYID'; 2401)
[2024-06-17T12:00:34.510+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-17T12:00:34.549+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
