[2024-06-20T09:36:19.047+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T09:36:19.085+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T09:32:39.273282+00:00 [queued]>
[2024-06-20T09:36:19.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T09:32:39.273282+00:00 [queued]>
[2024-06-20T09:36:19.102+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T09:36:19.127+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.fact_orders.run> on 2024-06-20 09:32:39.273282+00:00
[2024-06-20T09:36:19.139+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=7085) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T09:36:19.140+0000] {standard_task_runner.py:63} INFO - Started process 7091 to run task
[2024-06-20T09:36:19.140+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.fact_orders.run', 'manual__2024-06-20T09:32:39.273282+00:00', '--job-id', '437', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp0eevf94n']
[2024-06-20T09:36:19.144+0000] {standard_task_runner.py:91} INFO - Job 437: Subtask transform.fact_orders.run
[2024-06-20T09:36:19.174+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T09:36:19.237+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T09:32:39.273282+00:00 [running]> on host airflow-scheduler
[2024-06-20T09:36:19.409+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.fact_orders.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T09:32:39.273282+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T09:32:39.273282+00:00'
[2024-06-20T09:36:19.412+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T09:36:19.425+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T09:36:19.427+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp2_h77pze from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T09:36:19.437+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T09:36:19.489+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T09:36:19.491+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T09:36:19.494+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T09:36:19.501+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmps7kv7sax/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T09:36:19.503+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp2_h77pze', '--profiles-dir', '/tmp/tmps7kv7sax', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp2_h77pze
[2024-06-20T09:36:19.505+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T09:36:19.507+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp2_h77pze', '--profiles-dir', '/tmp/tmps7kv7sax', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T09:36:19.532+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T09:36:22.931+0000] {subprocess.py:94} INFO - [0m09:36:22  Running with dbt=1.8.2
[2024-06-20T09:36:23.248+0000] {subprocess.py:94} INFO - [0m09:36:23  Updating lock file in file path: /tmp/tmp2_h77pze/package-lock.yml
[2024-06-20T09:36:23.273+0000] {subprocess.py:94} INFO - [0m09:36:23  Installing dbt-labs/dbt_utils
[2024-06-20T09:36:23.733+0000] {subprocess.py:94} INFO - [0m09:36:23  Installed from version 0.8.6
[2024-06-20T09:36:23.734+0000] {subprocess.py:94} INFO - [0m09:36:23  Updated version available: 1.2.0
[2024-06-20T09:36:23.736+0000] {subprocess.py:94} INFO - [0m09:36:23
[2024-06-20T09:36:23.737+0000] {subprocess.py:94} INFO - [0m09:36:23  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T09:36:23.738+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T09:36:25.077+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T09:36:25.078+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T09:36:25.080+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmp2_h77pze', '--profiles-dir', '/tmp/tmps7kv7sax', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp2_h77pze
[2024-06-20T09:36:25.081+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T09:36:25.082+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmp2_h77pze', '--profiles-dir', '/tmp/tmps7kv7sax', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T09:36:25.098+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T09:36:28.499+0000] {subprocess.py:94} INFO - [0m09:36:28  Running with dbt=1.8.2
[2024-06-20T09:36:29.322+0000] {subprocess.py:94} INFO - [0m09:36:29  Registered adapter: snowflake=1.8.3
[2024-06-20T09:36:31.063+0000] {subprocess.py:94} INFO - [0m09:36:31  Found 20 models, 30 data tests, 11 sources, 682 macros
[2024-06-20T09:36:31.067+0000] {subprocess.py:94} INFO - [0m09:36:31
[2024-06-20T09:36:38.465+0000] {subprocess.py:94} INFO - [0m09:36:38  Concurrency: 1 threads (target='dev')
[2024-06-20T09:36:38.466+0000] {subprocess.py:94} INFO - [0m09:36:38
[2024-06-20T09:36:38.481+0000] {subprocess.py:94} INFO - [0m09:36:38  1 of 1 START sql table model dwh.fact_orders ................................... [RUN]
[2024-06-20T09:36:40.761+0000] {subprocess.py:94} INFO - [0m09:36:40  1 of 1 OK created sql table model dwh.fact_orders .............................. [[32mSUCCESS 1[0m in 2.28s]
[2024-06-20T09:36:40.770+0000] {subprocess.py:94} INFO - [0m09:36:40
[2024-06-20T09:36:40.771+0000] {subprocess.py:94} INFO - [0m09:36:40  Finished running 1 table model in 0 hours 0 minutes and 9.70 seconds (9.70s).
[2024-06-20T09:36:40.944+0000] {subprocess.py:94} INFO - [0m09:36:40
[2024-06-20T09:36:40.946+0000] {subprocess.py:94} INFO - [0m09:36:40  [32mCompleted successfully[0m
[2024-06-20T09:36:40.947+0000] {subprocess.py:94} INFO - [0m09:36:40
[2024-06-20T09:36:40.949+0000] {subprocess.py:94} INFO - [0m09:36:40  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T09:36:42.685+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T09:36:42.686+0000] {local.py:254} INFO - [0m09:36:40  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T09:36:42.724+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T09:36:42.725+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T09:36:42.739+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.dwh.dim_employees', extra=None), Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_orders', extra=None)]
[2024-06-20T09:36:42.740+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.dwh.fact_orders', extra=None)]
[2024-06-20T09:36:42.742+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T09:36:43.030+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-06-20T09:36:43.088+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T09:36:43.141+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.fact_orders.run, run_id=manual__2024-06-20T09:32:39.273282+00:00, execution_date=20240620T093239, start_date=20240620T093619, end_date=20240620T093643
[2024-06-20T09:36:43.222+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T09:36:43.293+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-20T09:36:43.300+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
