[2024-06-20T14:29:45.742+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T14:29:45.914+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_categories.run manual__2024-06-20T14:29:01.398557+00:00 [queued]>
[2024-06-20T14:29:45.994+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_categories.run manual__2024-06-20T14:29:01.398557+00:00 [queued]>
[2024-06-20T14:29:45.996+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T14:29:46.174+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_categories.run> on 2024-06-20 14:29:01.398557+00:00
[2024-06-20T14:29:46.221+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4077) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T14:29:46.229+0000] {standard_task_runner.py:63} INFO - Started process 4101 to run task
[2024-06-20T14:29:46.228+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_categories.run', 'manual__2024-06-20T14:29:01.398557+00:00', '--job-id', '603', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp65efqqdt']
[2024-06-20T14:29:46.248+0000] {standard_task_runner.py:91} INFO - Job 603: Subtask transform.raw_categories.run
[2024-06-20T14:29:46.372+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T14:29:46.799+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_categories.run manual__2024-06-20T14:29:01.398557+00:00 [running]> on host airflow-scheduler
[2024-06-20T14:29:47.575+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_categories.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T14:29:01.398557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T14:29:01.398557+00:00'
[2024-06-20T14:29:47.623+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T14:29:47.630+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T14:29:47.639+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp94bn3pik from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T14:29:47.690+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T14:29:47.901+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T14:29:47.920+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T14:29:47.928+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T14:29:47.943+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmp3bz9w1qz/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T14:29:47.954+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp94bn3pik', '--profiles-dir', '/tmp/tmp3bz9w1qz', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp94bn3pik
[2024-06-20T14:29:47.978+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T14:29:47.987+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp94bn3pik', '--profiles-dir', '/tmp/tmp3bz9w1qz', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T14:29:48.031+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T14:30:05.471+0000] {subprocess.py:94} INFO - [0m14:30:05  Running with dbt=1.8.2
[2024-06-20T14:30:07.026+0000] {subprocess.py:94} INFO - [0m14:30:07  Updating lock file in file path: /tmp/tmp94bn3pik/package-lock.yml
[2024-06-20T14:30:07.070+0000] {subprocess.py:94} INFO - [0m14:30:07  Installing dbt-labs/dbt_utils
[2024-06-20T14:30:07.985+0000] {subprocess.py:94} INFO - [0m14:30:07  Installed from version 0.8.6
[2024-06-20T14:30:07.988+0000] {subprocess.py:94} INFO - [0m14:30:07  Updated version available: 1.2.0
[2024-06-20T14:30:07.998+0000] {subprocess.py:94} INFO - [0m14:30:07
[2024-06-20T14:30:08.003+0000] {subprocess.py:94} INFO - [0m14:30:08  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T14:30:08.006+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T14:30:10.266+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T14:30:10.278+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T14:30:10.280+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_categories', '--project-dir', '/tmp/tmp94bn3pik', '--profiles-dir', '/tmp/tmp3bz9w1qz', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp94bn3pik
[2024-06-20T14:30:10.282+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T14:30:10.285+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_categories', '--project-dir', '/tmp/tmp94bn3pik', '--profiles-dir', '/tmp/tmp3bz9w1qz', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T14:30:10.381+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T14:30:23.172+0000] {subprocess.py:94} INFO - [0m14:30:23  Running with dbt=1.8.2
[2024-06-20T14:30:27.036+0000] {subprocess.py:94} INFO - [0m14:30:27  Registered adapter: snowflake=1.8.3
[2024-06-20T14:30:28.599+0000] {subprocess.py:94} INFO - [0m14:30:28  Unable to do partial parsing because profile has changed
[2024-06-20T14:30:47.676+0000] {subprocess.py:94} INFO - [0m14:30:47  [[33mWARNING[0m]: Did not find matching node for patch with name 'raw_employee_territores' in the 'models' section of file 'models/staging/schema.yml'
[2024-06-20T14:30:48.560+0000] {subprocess.py:94} INFO - [0m14:30:48  [[33mWARNING[0m]: Test 'test.dbt_project.not_null_raw_employee_territores_EMPLOYEEID.153e916ea2' (models/staging/schema.yml) depends on a node named 'raw_employee_territores' in package '' which was not found
[2024-06-20T14:30:48.562+0000] {subprocess.py:94} INFO - [0m14:30:48  [[33mWARNING[0m]: Test 'test.dbt_project.not_null_raw_employee_territores_TERRITORYID.3a9175e83e' (models/staging/schema.yml) depends on a node named 'raw_employee_territores' in package '' which was not found
[2024-06-20T14:30:51.500+0000] {subprocess.py:94} INFO - [0m14:30:51  Found 20 models, 27 data tests, 11 sources, 682 macros
[2024-06-20T14:30:51.512+0000] {subprocess.py:94} INFO - [0m14:30:51
[2024-06-20T14:31:00.159+0000] {subprocess.py:94} INFO - [0m14:31:00  Concurrency: 1 threads (target='dev')
[2024-06-20T14:31:00.168+0000] {subprocess.py:94} INFO - [0m14:31:00
[2024-06-20T14:31:00.282+0000] {subprocess.py:94} INFO - [0m14:31:00  1 of 1 START sql table model raw.raw_categories ................................ [RUN]
[2024-06-20T14:31:03.026+0000] {subprocess.py:94} INFO - [0m14:31:03  1 of 1 OK created sql table model raw.raw_categories ........................... [[32mSUCCESS 1[0m in 2.72s]
[2024-06-20T14:31:03.041+0000] {subprocess.py:94} INFO - [0m14:31:03
[2024-06-20T14:31:03.044+0000] {subprocess.py:94} INFO - [0m14:31:03  Finished running 1 table model in 0 hours 0 minutes and 11.52 seconds (11.52s).
[2024-06-20T14:31:03.424+0000] {subprocess.py:94} INFO - [0m14:31:03
[2024-06-20T14:31:03.429+0000] {subprocess.py:94} INFO - [0m14:31:03  [32mCompleted successfully[0m
[2024-06-20T14:31:03.430+0000] {subprocess.py:94} INFO - [0m14:31:03
[2024-06-20T14:31:03.432+0000] {subprocess.py:94} INFO - [0m14:31:03  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T14:31:09.123+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T14:31:09.126+0000] {local.py:254} INFO - [0m14:31:03  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T14:31:09.215+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T14:31:09.217+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T14:31:09.249+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.PUBLIC.categories', extra=None)]
[2024-06-20T14:31:09.251+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_categories', extra=None)]
[2024-06-20T14:31:09.256+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T14:31:11.867+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to 2024-06-20 00:00:00+00:00, run_after=2024-06-21 00:00:00+00:00
[2024-06-20T14:31:11.981+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/datasets/manager.py:53 SAWarning: DELETE statement on table 'task_outlet_dataset_reference' expected to delete 1 row(s); 0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
[2024-06-20T14:31:12.110+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T14:31:12.340+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_categories.run, run_id=manual__2024-06-20T14:29:01.398557+00:00, execution_date=20240620T142901, start_date=20240620T142945, end_date=20240620T143112
[2024-06-20T14:31:14.986+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T14:31:15.385+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-20T14:31:15.405+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
