[2024-06-20T14:32:25.967+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T14:32:26.048+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.test manual__2024-06-20T14:29:24.211440+00:00 [queued]>
[2024-06-20T14:32:26.104+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.test manual__2024-06-20T14:29:24.211440+00:00 [queued]>
[2024-06-20T14:32:26.105+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T14:32:26.177+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_orders.test> on 2024-06-20 14:29:24.211440+00:00
[2024-06-20T14:32:26.250+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4782) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T14:32:26.254+0000] {standard_task_runner.py:63} INFO - Started process 4805 to run task
[2024-06-20T14:32:26.247+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_orders.test', 'manual__2024-06-20T14:29:24.211440+00:00', '--job-id', '648', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp3e7yzd2o']
[2024-06-20T14:32:26.266+0000] {standard_task_runner.py:91} INFO - Job 648: Subtask transform.raw_orders.test
[2024-06-20T14:32:26.456+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T14:32:26.601+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_orders.test manual__2024-06-20T14:29:24.211440+00:00 [running]> on host airflow-scheduler
[2024-06-20T14:32:27.242+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_orders.test' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T14:29:24.211440+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T14:29:24.211440+00:00'
[2024-06-20T14:32:27.249+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T14:32:27.299+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T14:32:27.307+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp8jv80o11 from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T14:32:27.356+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T14:32:27.481+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T14:32:27.490+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T14:32:27.496+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T14:32:27.505+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmpx2tmbi0b/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T14:32:27.508+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp8jv80o11', '--profiles-dir', '/tmp/tmpx2tmbi0b', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp8jv80o11
[2024-06-20T14:32:27.515+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T14:32:27.519+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp8jv80o11', '--profiles-dir', '/tmp/tmpx2tmbi0b', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T14:32:27.581+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T14:32:42.933+0000] {subprocess.py:94} INFO - [0m14:32:42  Running with dbt=1.8.2
[2024-06-20T14:32:45.099+0000] {subprocess.py:94} INFO - [0m14:32:45  Updating lock file in file path: /tmp/tmp8jv80o11/package-lock.yml
[2024-06-20T14:32:45.148+0000] {subprocess.py:94} INFO - [0m14:32:45  Installing dbt-labs/dbt_utils
[2024-06-20T14:32:46.016+0000] {subprocess.py:94} INFO - [0m14:32:46  Installed from version 0.8.6
[2024-06-20T14:32:46.029+0000] {subprocess.py:94} INFO - [0m14:32:46  Updated version available: 1.2.0
[2024-06-20T14:32:46.033+0000] {subprocess.py:94} INFO - [0m14:32:46
[2024-06-20T14:32:46.046+0000] {subprocess.py:94} INFO - [0m14:32:46  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T14:32:46.047+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T14:32:49.038+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T14:32:49.042+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T14:32:49.045+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_orders', '--project-dir', '/tmp/tmp8jv80o11', '--profiles-dir', '/tmp/tmpx2tmbi0b', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp8jv80o11
[2024-06-20T14:32:49.048+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T14:32:49.050+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_orders', '--project-dir', '/tmp/tmp8jv80o11', '--profiles-dir', '/tmp/tmpx2tmbi0b', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T14:32:49.118+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T14:33:06.486+0000] {subprocess.py:94} INFO - [0m14:33:06  Running with dbt=1.8.2
[2024-06-20T14:33:10.120+0000] {subprocess.py:94} INFO - [0m14:33:10  Registered adapter: snowflake=1.8.3
[2024-06-20T14:33:15.661+0000] {subprocess.py:94} INFO - [0m14:33:15  Found 20 models, 27 data tests, 11 sources, 682 macros
[2024-06-20T14:33:15.694+0000] {subprocess.py:94} INFO - [0m14:33:15
[2024-06-20T14:33:23.080+0000] {subprocess.py:94} INFO - [0m14:33:23  Concurrency: 1 threads (target='dev')
[2024-06-20T14:33:23.091+0000] {subprocess.py:94} INFO - [0m14:33:23
[2024-06-20T14:33:23.233+0000] {subprocess.py:94} INFO - [0m14:33:23  1 of 1 START test not_null_raw_orders_ORDERID .................................. [RUN]
[2024-06-20T14:33:25.387+0000] {subprocess.py:94} INFO - [0m14:33:25  1 of 1 PASS not_null_raw_orders_ORDERID ........................................ [[32mPASS[0m in 2.16s]
[2024-06-20T14:33:25.405+0000] {subprocess.py:94} INFO - [0m14:33:25
[2024-06-20T14:33:25.409+0000] {subprocess.py:94} INFO - [0m14:33:25  Finished running 1 test in 0 hours 0 minutes and 9.72 seconds (9.72s).
[2024-06-20T14:33:26.186+0000] {subprocess.py:94} INFO - [0m14:33:26
[2024-06-20T14:33:26.194+0000] {subprocess.py:94} INFO - [0m14:33:26  [32mCompleted successfully[0m
[2024-06-20T14:33:26.200+0000] {subprocess.py:94} INFO - [0m14:33:26
[2024-06-20T14:33:26.204+0000] {subprocess.py:94} INFO - [0m14:33:26  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T14:33:29.672+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T14:33:29.674+0000] {local.py:254} INFO - [0m14:33:26  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T14:33:29.770+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T14:33:29.780+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T14:33:29.816+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_orders', extra=None)]
[2024-06-20T14:33:29.819+0000] {local.py:350} INFO - Outlets: []
[2024-06-20T14:33:29.833+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T14:33:30.995+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to 2024-06-20 00:00:00+00:00, run_after=2024-06-21 00:00:00+00:00
[2024-06-20T14:33:31.160+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T14:33:31.274+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_orders.test, run_id=manual__2024-06-20T14:29:24.211440+00:00, execution_date=20240620T142924, start_date=20240620T143226, end_date=20240620T143331
[2024-06-20T14:33:31.353+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T14:33:31.696+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T14:33:31.707+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
