[2024-06-20T08:44:27.858+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T08:44:27.889+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T08:41:09.652767+00:00 [queued]>
[2024-06-20T08:44:27.907+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T08:41:09.652767+00:00 [queued]>
[2024-06-20T08:44:27.908+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T08:44:27.933+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.fact_orders.run> on 2024-06-20 08:41:09.652767+00:00
[2024-06-20T08:44:27.944+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=3775) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T08:44:27.946+0000] {standard_task_runner.py:63} INFO - Started process 3779 to run task
[2024-06-20T08:44:27.944+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.fact_orders.run', 'manual__2024-06-20T08:41:09.652767+00:00', '--job-id', '266', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpsjrn7q8g']
[2024-06-20T08:44:27.947+0000] {standard_task_runner.py:91} INFO - Job 266: Subtask transform.fact_orders.run
[2024-06-20T08:44:27.971+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T08:44:28.029+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T08:41:09.652767+00:00 [running]> on host airflow-scheduler
[2024-06-20T08:44:28.171+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.fact_orders.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T08:41:09.652767+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T08:41:09.652767+00:00'
[2024-06-20T08:44:28.173+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T08:44:28.190+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T08:44:28.192+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpyt985udd from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T08:44:28.201+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T08:44:28.239+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T08:44:28.240+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T08:44:28.242+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T08:44:28.246+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmpt_8ks5k2/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T08:44:28.247+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpyt985udd', '--profiles-dir', '/tmp/tmpt_8ks5k2', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpyt985udd
[2024-06-20T08:44:28.249+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T08:44:28.251+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpyt985udd', '--profiles-dir', '/tmp/tmpt_8ks5k2', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T08:44:28.268+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T08:44:30.970+0000] {subprocess.py:94} INFO - [0m08:44:30  Running with dbt=1.8.2
[2024-06-20T08:44:31.444+0000] {subprocess.py:94} INFO - [0m08:44:31  Updating lock file in file path: /tmp/tmpyt985udd/package-lock.yml
[2024-06-20T08:44:31.461+0000] {subprocess.py:94} INFO - [0m08:44:31  Installing dbt-labs/dbt_utils
[2024-06-20T08:44:32.032+0000] {subprocess.py:94} INFO - [0m08:44:32  Installed from version 0.8.6
[2024-06-20T08:44:32.033+0000] {subprocess.py:94} INFO - [0m08:44:32  Updated version available: 1.2.0
[2024-06-20T08:44:32.035+0000] {subprocess.py:94} INFO - [0m08:44:32
[2024-06-20T08:44:32.037+0000] {subprocess.py:94} INFO - [0m08:44:32  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T08:44:32.038+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T08:44:33.543+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T08:44:33.544+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T08:44:33.546+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmpyt985udd', '--profiles-dir', '/tmp/tmpt_8ks5k2', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpyt985udd
[2024-06-20T08:44:33.547+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T08:44:33.549+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmpyt985udd', '--profiles-dir', '/tmp/tmpt_8ks5k2', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T08:44:33.564+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T08:44:36.027+0000] {subprocess.py:94} INFO - [0m08:44:36  Running with dbt=1.8.2
[2024-06-20T08:44:36.723+0000] {subprocess.py:94} INFO - [0m08:44:36  Registered adapter: snowflake=1.8.3
[2024-06-20T08:44:38.325+0000] {subprocess.py:94} INFO - [0m08:44:38  Found 20 models, 32 data tests, 11 sources, 682 macros
[2024-06-20T08:44:38.330+0000] {subprocess.py:94} INFO - [0m08:44:38
[2024-06-20T08:44:45.233+0000] {subprocess.py:94} INFO - [0m08:44:45  Concurrency: 1 threads (target='dev')
[2024-06-20T08:44:45.234+0000] {subprocess.py:94} INFO - [0m08:44:45
[2024-06-20T08:44:45.247+0000] {subprocess.py:94} INFO - [0m08:44:45  1 of 1 START sql table model dwh.fact_orders ................................... [RUN]
[2024-06-20T08:44:47.645+0000] {subprocess.py:94} INFO - [0m08:44:47  1 of 1 OK created sql table model dwh.fact_orders .............................. [[32mSUCCESS 1[0m in 2.39s]
[2024-06-20T08:44:47.653+0000] {subprocess.py:94} INFO - [0m08:44:47
[2024-06-20T08:44:47.654+0000] {subprocess.py:94} INFO - [0m08:44:47  Finished running 1 table model in 0 hours 0 minutes and 9.32 seconds (9.32s).
[2024-06-20T08:44:47.832+0000] {subprocess.py:94} INFO - [0m08:44:47
[2024-06-20T08:44:47.833+0000] {subprocess.py:94} INFO - [0m08:44:47  [32mCompleted successfully[0m
[2024-06-20T08:44:47.835+0000] {subprocess.py:94} INFO - [0m08:44:47
[2024-06-20T08:44:47.836+0000] {subprocess.py:94} INFO - [0m08:44:47  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T08:44:49.480+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T08:44:49.481+0000] {local.py:254} INFO - [0m08:44:47  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T08:44:49.507+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T08:44:49.508+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T08:44:49.516+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.dwh.dim_employees', extra=None), Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_orders', extra=None)]
[2024-06-20T08:44:49.517+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.dwh.fact_orders', extra=None)]
[2024-06-20T08:44:49.519+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T08:44:49.761+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-06-20T08:44:49.822+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T08:44:49.877+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.fact_orders.run, run_id=manual__2024-06-20T08:41:09.652767+00:00, execution_date=20240620T084109, start_date=20240620T084427, end_date=20240620T084449
[2024-06-20T08:44:49.945+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T08:44:49.962+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
