[2024-06-20T07:42:09.525+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T07:42:09.657+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_order_details.test manual__2024-06-20T07:39:50.213563+00:00 [queued]>
[2024-06-20T07:42:09.692+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_order_details.test manual__2024-06-20T07:39:50.213563+00:00 [queued]>
[2024-06-20T07:42:09.693+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T07:42:09.765+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_order_details.test> on 2024-06-20 07:39:50.213563+00:00
[2024-06-20T07:42:09.792+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_order_details.test', 'manual__2024-06-20T07:39:50.213563+00:00', '--job-id', '197', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpxu7zwuck']
[2024-06-20T07:42:09.800+0000] {standard_task_runner.py:91} INFO - Job 197: Subtask transform.raw_order_details.test
[2024-06-20T07:42:09.890+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1574) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T07:42:09.893+0000] {standard_task_runner.py:63} INFO - Started process 1589 to run task
[2024-06-20T07:42:09.894+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T07:42:10.099+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_order_details.test manual__2024-06-20T07:39:50.213563+00:00 [running]> on host airflow-scheduler
[2024-06-20T07:42:10.605+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_order_details.test' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T07:39:50.213563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T07:39:50.213563+00:00'
[2024-06-20T07:42:10.608+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T07:42:10.649+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T07:42:10.652+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpo5p4fyyy from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T07:42:10.672+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T07:42:10.799+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T07:42:10.809+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T07:42:10.812+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T07:42:10.832+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmpsajg_gt1/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T07:42:10.834+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpo5p4fyyy', '--profiles-dir', '/tmp/tmpsajg_gt1', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpo5p4fyyy
[2024-06-20T07:42:10.838+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T07:42:10.840+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpo5p4fyyy', '--profiles-dir', '/tmp/tmpsajg_gt1', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T07:42:10.915+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T07:42:20.466+0000] {subprocess.py:94} INFO - [0m07:42:20  Running with dbt=1.8.2
[2024-06-20T07:42:21.337+0000] {subprocess.py:94} INFO - [0m07:42:21  Updating lock file in file path: /tmp/tmpo5p4fyyy/package-lock.yml
[2024-06-20T07:42:21.361+0000] {subprocess.py:94} INFO - [0m07:42:21  Installing dbt-labs/dbt_utils
[2024-06-20T07:42:22.061+0000] {subprocess.py:94} INFO - [0m07:42:22  Installed from version 0.8.6
[2024-06-20T07:42:22.070+0000] {subprocess.py:94} INFO - [0m07:42:22  Updated version available: 1.2.0
[2024-06-20T07:42:22.078+0000] {subprocess.py:94} INFO - [0m07:42:22
[2024-06-20T07:42:22.083+0000] {subprocess.py:94} INFO - [0m07:42:22  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T07:42:22.086+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T07:42:23.596+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T07:42:23.598+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T07:42:23.601+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_order_details', '--project-dir', '/tmp/tmpo5p4fyyy', '--profiles-dir', '/tmp/tmpsajg_gt1', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpo5p4fyyy
[2024-06-20T07:42:23.605+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T07:42:23.608+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_order_details', '--project-dir', '/tmp/tmpo5p4fyyy', '--profiles-dir', '/tmp/tmpsajg_gt1', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T07:42:23.638+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T07:42:34.484+0000] {subprocess.py:94} INFO - [0m07:42:34  Running with dbt=1.8.2
[2024-06-20T07:42:37.332+0000] {subprocess.py:94} INFO - [0m07:42:37  Registered adapter: snowflake=1.8.3
[2024-06-20T07:42:42.192+0000] {subprocess.py:94} INFO - [0m07:42:42  Found 20 models, 32 data tests, 11 sources, 682 macros
[2024-06-20T07:42:42.205+0000] {subprocess.py:94} INFO - [0m07:42:42
[2024-06-20T07:42:47.571+0000] {subprocess.py:94} INFO - [0m07:42:47  Concurrency: 1 threads (target='dev')
[2024-06-20T07:42:47.574+0000] {subprocess.py:94} INFO - [0m07:42:47
[2024-06-20T07:42:47.644+0000] {subprocess.py:94} INFO - [0m07:42:47  1 of 3 START test not_null_raw_order_details_ORDERDETAILID ..................... [RUN]
[2024-06-20T07:42:49.520+0000] {subprocess.py:94} INFO - [0m07:42:49  1 of 3 ERROR not_null_raw_order_details_ORDERDETAILID .......................... [[31mERROR[0m in 1.87s]
[2024-06-20T07:42:49.528+0000] {subprocess.py:94} INFO - [0m07:42:49  2 of 3 START test not_null_raw_order_details_ORDERID ........................... [RUN]
[2024-06-20T07:42:51.581+0000] {subprocess.py:94} INFO - [0m07:42:51  2 of 3 PASS not_null_raw_order_details_ORDERID ................................. [[32mPASS[0m in 2.05s]
[2024-06-20T07:42:51.594+0000] {subprocess.py:94} INFO - [0m07:42:51  3 of 3 START test not_null_raw_order_details_PRODUCTID ......................... [RUN]
[2024-06-20T07:42:54.755+0000] {subprocess.py:94} INFO - [0m07:42:54  3 of 3 PASS not_null_raw_order_details_PRODUCTID ............................... [[32mPASS[0m in 3.16s]
[2024-06-20T07:42:54.774+0000] {subprocess.py:94} INFO - [0m07:42:54
[2024-06-20T07:42:54.780+0000] {subprocess.py:94} INFO - [0m07:42:54  Finished running 3 data tests in 0 hours 0 minutes and 12.57 seconds (12.57s).
[2024-06-20T07:42:55.085+0000] {subprocess.py:94} INFO - [0m07:42:55
[2024-06-20T07:42:55.088+0000] {subprocess.py:94} INFO - [0m07:42:55  [31mCompleted with 1 error and 0 warnings:[0m
[2024-06-20T07:42:55.090+0000] {subprocess.py:94} INFO - [0m07:42:55
[2024-06-20T07:42:55.091+0000] {subprocess.py:94} INFO - [0m07:42:55    Database Error in test not_null_raw_order_details_ORDERDETAILID (models/staging/schema.yml)
[2024-06-20T07:42:55.094+0000] {subprocess.py:94} INFO -   000904 (42000): SQL compilation error: error line 12 at position 7
[2024-06-20T07:42:55.096+0000] {subprocess.py:94} INFO -   invalid identifier 'ORDERDETAILID'
[2024-06-20T07:42:55.099+0000] {subprocess.py:94} INFO -   compiled Code at target/run/dbt_project/models/staging/schema.yml/not_null_raw_order_details_ORDERDETAILID.sql
[2024-06-20T07:42:55.101+0000] {subprocess.py:94} INFO - [0m07:42:55
[2024-06-20T07:42:55.103+0000] {subprocess.py:94} INFO - [0m07:42:55  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
[2024-06-20T07:42:57.118+0000] {subprocess.py:98} INFO - Command exited with return code 1
[2024-06-20T07:42:57.121+0000] {local.py:254} INFO - [0m07:42:55  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
[2024-06-20T07:42:57.185+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T07:42:57.189+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T07:42:57.206+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_order_details', extra=None)]
[2024-06-20T07:42:57.207+0000] {local.py:350} INFO - Outlets: []
[2024-06-20T07:42:57.210+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T07:42:57.621+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-06-20T07:42:57.684+0000] {local.py:184} ERROR - [0m07:42:34  Running with dbt=1.8.2
[0m07:42:37  Registered adapter: snowflake=1.8.3
[0m07:42:42  Found 20 models, 32 data tests, 11 sources, 682 macros
[0m07:42:42
[0m07:42:47  Concurrency: 1 threads (target='dev')
[0m07:42:47
[0m07:42:47  1 of 3 START test not_null_raw_order_details_ORDERDETAILID ..................... [RUN]
[0m07:42:49  1 of 3 ERROR not_null_raw_order_details_ORDERDETAILID .......................... [[31mERROR[0m in 1.87s]
[0m07:42:49  2 of 3 START test not_null_raw_order_details_ORDERID ........................... [RUN]
[0m07:42:51  2 of 3 PASS not_null_raw_order_details_ORDERID ................................. [[32mPASS[0m in 2.05s]
[0m07:42:51  3 of 3 START test not_null_raw_order_details_PRODUCTID ......................... [RUN]
[0m07:42:54  3 of 3 PASS not_null_raw_order_details_PRODUCTID ............................... [[32mPASS[0m in 3.16s]
[0m07:42:54
[0m07:42:54  Finished running 3 data tests in 0 hours 0 minutes and 12.57 seconds (12.57s).
[0m07:42:55
[0m07:42:55  [31mCompleted with 1 error and 0 warnings:[0m
[0m07:42:55
[0m07:42:55    Database Error in test not_null_raw_order_details_ORDERDETAILID (models/staging/schema.yml)
  000904 (42000): SQL compilation error: error line 12 at position 7
  invalid identifier 'ORDERDETAILID'
  compiled Code at target/run/dbt_project/models/staging/schema.yml/not_null_raw_order_details_ORDERDETAILID.sql
[0m07:42:55
[0m07:42:55  Done. PASS=2 WARN=0 ERROR=1 SKIP=0 TOTAL=3
[2024-06-20T07:42:57.716+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T07:42:57.748+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 579, in execute
    result = self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 489, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 359, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 185, in handle_exception_subprocess
    raise AirflowException(f"dbt command failed. The command returned a non-zero exit code {result.exit_code}.")
airflow.exceptions.AirflowException: dbt command failed. The command returned a non-zero exit code 1.
[2024-06-20T07:42:57.757+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=ELT-PROJECT, task_id=transform.raw_order_details.test, run_id=manual__2024-06-20T07:39:50.213563+00:00, execution_date=20240620T073950, start_date=20240620T074209, end_date=20240620T074257
[2024-06-20T07:42:57.780+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 197 for task transform.raw_order_details.test (dbt command failed. The command returned a non-zero exit code 1.; 1589)
[2024-06-20T07:42:57.808+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T07:42:57.896+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T07:42:57.900+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
