[2024-06-20T14:30:40.099+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T14:30:40.498+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_categories.run manual__2024-06-20T14:29:24.211440+00:00 [queued]>
[2024-06-20T14:30:40.646+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_categories.run manual__2024-06-20T14:29:24.211440+00:00 [queued]>
[2024-06-20T14:30:40.656+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T14:30:40.842+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_categories.run> on 2024-06-20 14:29:24.211440+00:00
[2024-06-20T14:30:40.931+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4312) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T14:30:40.933+0000] {standard_task_runner.py:63} INFO - Started process 4336 to run task
[2024-06-20T14:30:40.913+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_categories.run', 'manual__2024-06-20T14:29:24.211440+00:00', '--job-id', '627', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp2dyi0vsv']
[2024-06-20T14:30:40.953+0000] {standard_task_runner.py:91} INFO - Job 627: Subtask transform.raw_categories.run
[2024-06-20T14:30:41.116+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T14:30:41.465+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_categories.run manual__2024-06-20T14:29:24.211440+00:00 [running]> on host airflow-scheduler
[2024-06-20T14:30:42.233+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_categories.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T14:29:24.211440+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T14:29:24.211440+00:00'
[2024-06-20T14:30:42.238+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T14:30:42.252+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T14:30:42.260+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpo0z3idu1 from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T14:30:42.284+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T14:30:42.683+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T14:30:42.689+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T14:30:42.705+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T14:30:42.737+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmpyjwhh2te/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T14:30:42.756+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpo0z3idu1', '--profiles-dir', '/tmp/tmpyjwhh2te', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpo0z3idu1
[2024-06-20T14:30:42.774+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T14:30:42.781+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpo0z3idu1', '--profiles-dir', '/tmp/tmpyjwhh2te', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T14:30:42.881+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T14:30:59.377+0000] {subprocess.py:94} INFO - [0m14:30:59  Running with dbt=1.8.2
[2024-06-20T14:31:00.323+0000] {subprocess.py:94} INFO - [0m14:31:00  Updating lock file in file path: /tmp/tmpo0z3idu1/package-lock.yml
[2024-06-20T14:31:00.378+0000] {subprocess.py:94} INFO - [0m14:31:00  Installing dbt-labs/dbt_utils
[2024-06-20T14:31:01.384+0000] {subprocess.py:94} INFO - [0m14:31:01  Installed from version 0.8.6
[2024-06-20T14:31:01.392+0000] {subprocess.py:94} INFO - [0m14:31:01  Updated version available: 1.2.0
[2024-06-20T14:31:01.397+0000] {subprocess.py:94} INFO - [0m14:31:01
[2024-06-20T14:31:01.400+0000] {subprocess.py:94} INFO - [0m14:31:01  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T14:31:01.403+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T14:31:08.051+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T14:31:08.053+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T14:31:08.059+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_categories', '--project-dir', '/tmp/tmpo0z3idu1', '--profiles-dir', '/tmp/tmpyjwhh2te', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpo0z3idu1
[2024-06-20T14:31:08.063+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T14:31:08.066+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_categories', '--project-dir', '/tmp/tmpo0z3idu1', '--profiles-dir', '/tmp/tmpyjwhh2te', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T14:31:08.151+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T14:31:21.076+0000] {subprocess.py:94} INFO - [0m14:31:21  Running with dbt=1.8.2
[2024-06-20T14:31:25.624+0000] {subprocess.py:94} INFO - [0m14:31:25  Registered adapter: snowflake=1.8.3
[2024-06-20T14:31:27.005+0000] {subprocess.py:94} INFO - [0m14:31:27  Unable to do partial parsing because profile has changed
[2024-06-20T14:31:46.308+0000] {subprocess.py:94} INFO - [0m14:31:46  [[33mWARNING[0m]: Did not find matching node for patch with name 'raw_employee_territores' in the 'models' section of file 'models/staging/schema.yml'
[2024-06-20T14:31:46.691+0000] {subprocess.py:94} INFO - [0m14:31:46  [[33mWARNING[0m]: Test 'test.dbt_project.not_null_raw_employee_territores_EMPLOYEEID.153e916ea2' (models/staging/schema.yml) depends on a node named 'raw_employee_territores' in package '' which was not found
[2024-06-20T14:31:46.696+0000] {subprocess.py:94} INFO - [0m14:31:46  [[33mWARNING[0m]: Test 'test.dbt_project.not_null_raw_employee_territores_TERRITORYID.3a9175e83e' (models/staging/schema.yml) depends on a node named 'raw_employee_territores' in package '' which was not found
[2024-06-20T14:31:48.065+0000] {subprocess.py:94} INFO - [0m14:31:48  Found 20 models, 27 data tests, 11 sources, 682 macros
[2024-06-20T14:31:48.089+0000] {subprocess.py:94} INFO - [0m14:31:48
[2024-06-20T14:31:56.701+0000] {subprocess.py:94} INFO - [0m14:31:56  Concurrency: 1 threads (target='dev')
[2024-06-20T14:31:56.703+0000] {subprocess.py:94} INFO - [0m14:31:56
[2024-06-20T14:31:56.906+0000] {subprocess.py:94} INFO - [0m14:31:56  1 of 1 START sql table model raw.raw_categories ................................ [RUN]
[2024-06-20T14:31:59.846+0000] {subprocess.py:94} INFO - [0m14:31:59  1 of 1 OK created sql table model raw.raw_categories ........................... [[32mSUCCESS 1[0m in 2.93s]
[2024-06-20T14:31:59.866+0000] {subprocess.py:94} INFO - [0m14:31:59
[2024-06-20T14:31:59.871+0000] {subprocess.py:94} INFO - [0m14:31:59  Finished running 1 table model in 0 hours 0 minutes and 11.77 seconds (11.77s).
[2024-06-20T14:32:01.132+0000] {subprocess.py:94} INFO - [0m14:32:01
[2024-06-20T14:32:01.139+0000] {subprocess.py:94} INFO - [0m14:32:01  [32mCompleted successfully[0m
[2024-06-20T14:32:01.141+0000] {subprocess.py:94} INFO - [0m14:32:01
[2024-06-20T14:32:01.167+0000] {subprocess.py:94} INFO - [0m14:32:01  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T14:32:04.822+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T14:32:04.825+0000] {local.py:254} INFO - [0m14:32:01  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T14:32:04.974+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T14:32:04.982+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T14:32:05.043+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.PUBLIC.categories', extra=None)]
[2024-06-20T14:32:05.060+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_categories', extra=None)]
[2024-06-20T14:32:05.063+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T14:32:07.502+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to 2024-06-20 00:00:00+00:00, run_after=2024-06-21 00:00:00+00:00
[2024-06-20T14:32:08.029+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T14:32:08.258+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_categories.run, run_id=manual__2024-06-20T14:29:24.211440+00:00, execution_date=20240620T142924, start_date=20240620T143040, end_date=20240620T143208
[2024-06-20T14:32:08.393+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T14:32:08.563+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-20T14:32:08.574+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
