[2024-06-20T09:33:15.330+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T09:33:15.520+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.run manual__2024-06-20T09:32:39.273282+00:00 [queued]>
[2024-06-20T09:33:15.594+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.run manual__2024-06-20T09:32:39.273282+00:00 [queued]>
[2024-06-20T09:33:15.595+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T09:33:15.684+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_orders.run> on 2024-06-20 09:32:39.273282+00:00
[2024-06-20T09:33:15.755+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=6654) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T09:33:15.764+0000] {standard_task_runner.py:63} INFO - Started process 6685 to run task
[2024-06-20T09:33:15.766+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_orders.run', 'manual__2024-06-20T09:32:39.273282+00:00', '--job-id', '416', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmp4w9yxc1c']
[2024-06-20T09:33:15.805+0000] {standard_task_runner.py:91} INFO - Job 416: Subtask transform.raw_orders.run
[2024-06-20T09:33:15.885+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T09:33:16.168+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_orders.run manual__2024-06-20T09:32:39.273282+00:00 [running]> on host airflow-scheduler
[2024-06-20T09:33:16.730+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_orders.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T09:32:39.273282+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T09:32:39.273282+00:00'
[2024-06-20T09:33:16.737+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T09:33:16.777+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T09:33:16.781+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpztfr4ezc from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T09:33:16.795+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T09:33:16.935+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T09:33:16.943+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T09:33:16.948+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T09:33:16.966+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmp19azp5fc/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T09:33:16.972+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpztfr4ezc', '--profiles-dir', '/tmp/tmp19azp5fc', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpztfr4ezc
[2024-06-20T09:33:16.975+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T09:33:16.977+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpztfr4ezc', '--profiles-dir', '/tmp/tmp19azp5fc', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T09:33:17.031+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T09:33:34.556+0000] {subprocess.py:94} INFO - [0m09:33:34  Running with dbt=1.8.2
[2024-06-20T09:33:36.564+0000] {subprocess.py:94} INFO - [0m09:33:36  Updating lock file in file path: /tmp/tmpztfr4ezc/package-lock.yml
[2024-06-20T09:33:36.594+0000] {subprocess.py:94} INFO - [0m09:33:36  Installing dbt-labs/dbt_utils
[2024-06-20T09:33:37.226+0000] {subprocess.py:94} INFO - [0m09:33:37  Installed from version 0.8.6
[2024-06-20T09:33:37.230+0000] {subprocess.py:94} INFO - [0m09:33:37  Updated version available: 1.2.0
[2024-06-20T09:33:37.236+0000] {subprocess.py:94} INFO - [0m09:33:37
[2024-06-20T09:33:37.239+0000] {subprocess.py:94} INFO - [0m09:33:37  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T09:33:37.243+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T09:33:39.118+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T09:33:39.128+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T09:33:39.141+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_orders', '--project-dir', '/tmp/tmpztfr4ezc', '--profiles-dir', '/tmp/tmp19azp5fc', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpztfr4ezc
[2024-06-20T09:33:39.145+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T09:33:39.158+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_orders', '--project-dir', '/tmp/tmpztfr4ezc', '--profiles-dir', '/tmp/tmp19azp5fc', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T09:33:39.235+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T09:33:55.175+0000] {subprocess.py:94} INFO - [0m09:33:55  Running with dbt=1.8.2
[2024-06-20T09:33:58.608+0000] {subprocess.py:94} INFO - [0m09:33:58  Registered adapter: snowflake=1.8.3
[2024-06-20T09:34:01.523+0000] {subprocess.py:94} INFO - [0m09:34:01  Found 20 models, 30 data tests, 11 sources, 682 macros
[2024-06-20T09:34:01.534+0000] {subprocess.py:94} INFO - [0m09:34:01
[2024-06-20T09:34:09.049+0000] {subprocess.py:94} INFO - [0m09:34:09  Concurrency: 1 threads (target='dev')
[2024-06-20T09:34:09.051+0000] {subprocess.py:94} INFO - [0m09:34:09
[2024-06-20T09:34:09.072+0000] {subprocess.py:94} INFO - [0m09:34:09  1 of 1 START sql table model raw.raw_orders .................................... [RUN]
[2024-06-20T09:34:12.096+0000] {subprocess.py:94} INFO - [0m09:34:12  1 of 1 OK created sql table model raw.raw_orders ............................... [[32mSUCCESS 1[0m in 3.00s]
[2024-06-20T09:34:12.130+0000] {subprocess.py:94} INFO - [0m09:34:12
[2024-06-20T09:34:12.133+0000] {subprocess.py:94} INFO - [0m09:34:12  Finished running 1 table model in 0 hours 0 minutes and 10.59 seconds (10.59s).
[2024-06-20T09:34:13.033+0000] {subprocess.py:94} INFO - [0m09:34:13
[2024-06-20T09:34:13.044+0000] {subprocess.py:94} INFO - [0m09:34:13  [32mCompleted successfully[0m
[2024-06-20T09:34:13.047+0000] {subprocess.py:94} INFO - [0m09:34:13
[2024-06-20T09:34:13.049+0000] {subprocess.py:94} INFO - [0m09:34:13  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T09:34:15.477+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T09:34:15.481+0000] {local.py:254} INFO - [0m09:34:13  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T09:34:16.565+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T09:34:16.576+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T09:34:16.664+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.PUBLIC.orders', extra=None)]
[2024-06-20T09:34:16.677+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_orders', extra=None)]
[2024-06-20T09:34:16.680+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T09:34:17.020+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-06-20T09:34:17.144+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/datasets/manager.py:53 SAWarning: DELETE statement on table 'task_outlet_dataset_reference' expected to delete 1 row(s); 0 were matched.  Please set confirm_deleted_rows=False within the mapper configuration to prevent this warning.
[2024-06-20T09:34:17.341+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T09:34:17.522+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_orders.run, run_id=manual__2024-06-20T09:32:39.273282+00:00, execution_date=20240620T093239, start_date=20240620T093315, end_date=20240620T093417
[2024-06-20T09:34:17.791+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T09:34:17.838+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
