[2024-06-20T07:35:59.155+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T07:35:59.304+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_products.run manual__2024-06-20T07:29:25.850609+00:00 [queued]>
[2024-06-20T07:35:59.345+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_products.run manual__2024-06-20T07:29:25.850609+00:00 [queued]>
[2024-06-20T07:35:59.346+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-06-20T07:35:59.406+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.raw_products.run> on 2024-06-20 07:29:25.850609+00:00
[2024-06-20T07:35:59.437+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=958) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T07:35:59.436+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_products.run', 'manual__2024-06-20T07:29:25.850609+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpcw2grkp_']
[2024-06-20T07:35:59.441+0000] {standard_task_runner.py:63} INFO - Started process 980 to run task
[2024-06-20T07:35:59.442+0000] {standard_task_runner.py:91} INFO - Job 148: Subtask transform.raw_products.run
[2024-06-20T07:35:59.523+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T07:35:59.715+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_products.run manual__2024-06-20T07:29:25.850609+00:00 [running]> on host airflow-scheduler
[2024-06-20T07:36:00.246+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_products.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T07:29:25.850609+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T07:29:25.850609+00:00'
[2024-06-20T07:36:00.258+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T07:36:00.307+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T07:36:00.323+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpbum9gkew from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T07:36:00.380+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T07:36:00.555+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T07:36:00.574+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T07:36:00.577+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T07:36:00.596+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmpp8mzuehj/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T07:36:00.599+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_products', '--project-dir', '/tmp/tmpbum9gkew', '--profiles-dir', '/tmp/tmpp8mzuehj', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpbum9gkew
[2024-06-20T07:36:00.610+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T07:36:00.617+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'raw_products', '--project-dir', '/tmp/tmpbum9gkew', '--profiles-dir', '/tmp/tmpp8mzuehj', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T07:36:00.711+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T07:36:13.092+0000] {subprocess.py:94} INFO - [0m07:36:13  Running with dbt=1.8.2
[2024-06-20T07:36:15.726+0000] {subprocess.py:94} INFO - [0m07:36:15  Registered adapter: snowflake=1.8.3
[2024-06-20T07:36:15.745+0000] {subprocess.py:94} INFO - [0m07:36:15  Encountered an error:
[2024-06-20T07:36:15.756+0000] {subprocess.py:94} INFO - Compilation Error
[2024-06-20T07:36:15.758+0000] {subprocess.py:94} INFO -   dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
[2024-06-20T07:36:17.730+0000] {subprocess.py:98} INFO - Command exited with return code 2
[2024-06-20T07:36:17.733+0000] {local.py:254} INFO -   dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
[2024-06-20T07:36:18.686+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T07:36:18.690+0000] {local.py:349} INFO - Inlets: []
[2024-06-20T07:36:18.706+0000] {local.py:350} INFO - Outlets: []
[2024-06-20T07:36:18.710+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T07:36:18.776+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-06-20T07:36:18.938+0000] {local.py:184} ERROR - [0m07:36:13  Running with dbt=1.8.2
[0m07:36:15  Registered adapter: snowflake=1.8.3
[0m07:36:15  Encountered an error:
Compilation Error
  dbt found 1 package(s) specified in packages.yml, but only 0 package(s) installed in dbt_packages. Run "dbt deps" to install package dependencies.
[2024-06-20T07:36:18.944+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T07:36:19.019+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/base.py", line 264, in execute
    self.build_and_run_cmd(context=context, cmd_flags=self.add_cmd_flags())
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 489, in build_and_run_cmd
    result = self.run_command(cmd=dbt_cmd, env=env, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 359, in run_command
    self.handle_exception(result)
  File "/home/airflow/.local/lib/python3.12/site-packages/cosmos/operators/local.py", line 185, in handle_exception_subprocess
    raise AirflowException(f"dbt command failed. The command returned a non-zero exit code {result.exit_code}.")
airflow.exceptions.AirflowException: dbt command failed. The command returned a non-zero exit code 2.
[2024-06-20T07:36:19.075+0000] {taskinstance.py:222} INFO - Forcing task transform.raw_territories.run to fail due to dag's `fail_stop` setting
[2024-06-20T07:36:19.077+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-20T07:36:19.126+0000] {taskinstance.py:225} INFO - Setting task transform.raw_categories.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.139+0000] {taskinstance.py:225} INFO - Setting task transform.raw_customers.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.145+0000] {taskinstance.py:225} INFO - Setting task transform.raw_employees.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.147+0000] {taskinstance.py:222} INFO - Forcing task transform.raw_employees.run to fail due to dag's `fail_stop` setting
[2024-06-20T07:36:19.149+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-20T07:36:19.201+0000] {taskinstance.py:222} INFO - Forcing task transform.raw_categories.run to fail due to dag's `fail_stop` setting
[2024-06-20T07:36:19.209+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-20T07:36:19.280+0000] {taskinstance.py:222} INFO - Forcing task transform.raw_customers.run to fail due to dag's `fail_stop` setting
[2024-06-20T07:36:19.286+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-20T07:36:19.360+0000] {taskinstance.py:222} INFO - Forcing task transform.raw_employee_territories_run to fail due to dag's `fail_stop` setting
[2024-06-20T07:36:19.367+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-20T07:36:19.477+0000] {taskinstance.py:225} INFO - Setting task transform.raw_orders.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.488+0000] {taskinstance.py:225} INFO - Setting task transform.raw_order_details.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.489+0000] {taskinstance.py:225} INFO - Setting task transform.raw_products.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.490+0000] {taskinstance.py:225} INFO - Setting task transform.raw_regions.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.491+0000] {taskinstance.py:225} INFO - Setting task transform.raw_shippers.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.492+0000] {taskinstance.py:225} INFO - Setting task transform.raw_suppliers.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.493+0000] {taskinstance.py:225} INFO - Setting task transform.raw_territories.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.494+0000] {taskinstance.py:225} INFO - Setting task transform.dim_employees.run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.495+0000] {taskinstance.py:225} INFO - Setting task transform.dim_employees.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.497+0000] {taskinstance.py:225} INFO - Setting task transform.dim_categories.run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.498+0000] {taskinstance.py:225} INFO - Setting task transform.dim_categories.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.499+0000] {taskinstance.py:225} INFO - Setting task transform.dim_suppliers.run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.501+0000] {taskinstance.py:225} INFO - Setting task transform.dim_suppliers.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.502+0000] {taskinstance.py:225} INFO - Setting task transform.dim_products.run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.503+0000] {taskinstance.py:225} INFO - Setting task transform.dim_products.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.505+0000] {taskinstance.py:225} INFO - Setting task transform.fact_orders.run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.516+0000] {taskinstance.py:225} INFO - Setting task transform.fact_orders.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.519+0000] {taskinstance.py:225} INFO - Setting task transform.fact_order_details.run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.520+0000] {taskinstance.py:225} INFO - Setting task transform.fact_order_details.test to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.521+0000] {taskinstance.py:225} INFO - Setting task transform.gross_revenue_run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.523+0000] {taskinstance.py:225} INFO - Setting task transform.best_employee_run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.525+0000] {taskinstance.py:225} INFO - Setting task transform.popular_product_categories_run to SKIPPED due to dag's `fail_stop` setting.
[2024-06-20T07:36:19.526+0000] {taskinstance.py:222} INFO - Forcing task transform.raw_order_details.run to fail due to dag's `fail_stop` setting
[2024-06-20T07:36:19.527+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-20T07:36:20.649+0000] {taskinstance.py:222} INFO - Forcing task transform.raw_orders.run to fail due to dag's `fail_stop` setting
[2024-06-20T07:36:20.650+0000] {taskinstance.py:1774} ERROR - Recording the task instance as FAILED
[2024-06-20T07:36:20.679+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=ELT-PROJECT, task_id=transform.raw_products.run, run_id=manual__2024-06-20T07:29:25.850609+00:00, execution_date=20240620T072925, start_date=20240620T073559, end_date=20240620T073619
[2024-06-20T07:36:20.794+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 148 for task transform.raw_products.run (dbt command failed. The command returned a non-zero exit code 2.; 980)
[2024-06-20T07:36:20.847+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-20T07:36:20.944+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-20T07:36:20.956+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
