[2024-06-20T09:13:47.064+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T09:13:47.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T09:10:32.865792+00:00 [queued]>
[2024-06-20T09:13:47.101+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T09:10:32.865792+00:00 [queued]>
[2024-06-20T09:13:47.102+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T09:13:47.120+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.fact_orders.run> on 2024-06-20 09:10:32.865792+00:00
[2024-06-20T09:13:47.129+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=5892) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T09:13:47.130+0000] {standard_task_runner.py:63} INFO - Started process 5894 to run task
[2024-06-20T09:13:47.129+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.fact_orders.run', 'manual__2024-06-20T09:10:32.865792+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpblyp7rug']
[2024-06-20T09:13:47.132+0000] {standard_task_runner.py:91} INFO - Job 378: Subtask transform.fact_orders.run
[2024-06-20T09:13:47.154+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T09:13:47.198+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T09:10:32.865792+00:00 [running]> on host airflow-scheduler
[2024-06-20T09:13:47.315+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.fact_orders.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T09:10:32.865792+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T09:10:32.865792+00:00'
[2024-06-20T09:13:47.316+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T09:13:47.330+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T09:13:47.331+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpo_gpmwak from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T09:13:47.340+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T09:13:47.370+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T09:13:47.371+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T09:13:47.372+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T09:13:47.374+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmpb2bp08dm/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T09:13:47.376+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpo_gpmwak', '--profiles-dir', '/tmp/tmpb2bp08dm', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpo_gpmwak
[2024-06-20T09:13:47.377+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T09:13:47.378+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpo_gpmwak', '--profiles-dir', '/tmp/tmpb2bp08dm', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T09:13:47.392+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T09:13:50.235+0000] {subprocess.py:94} INFO - [0m09:13:50  Running with dbt=1.8.2
[2024-06-20T09:13:50.792+0000] {subprocess.py:94} INFO - [0m09:13:50  Updating lock file in file path: /tmp/tmpo_gpmwak/package-lock.yml
[2024-06-20T09:13:50.803+0000] {subprocess.py:94} INFO - [0m09:13:50  Installing dbt-labs/dbt_utils
[2024-06-20T09:13:51.338+0000] {subprocess.py:94} INFO - [0m09:13:51  Installed from version 0.8.6
[2024-06-20T09:13:51.339+0000] {subprocess.py:94} INFO - [0m09:13:51  Updated version available: 1.2.0
[2024-06-20T09:13:51.341+0000] {subprocess.py:94} INFO - [0m09:13:51
[2024-06-20T09:13:51.342+0000] {subprocess.py:94} INFO - [0m09:13:51  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T09:13:51.344+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T09:13:52.772+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T09:13:52.774+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T09:13:52.775+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmpo_gpmwak', '--profiles-dir', '/tmp/tmpb2bp08dm', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpo_gpmwak
[2024-06-20T09:13:52.776+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T09:13:52.777+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmpo_gpmwak', '--profiles-dir', '/tmp/tmpb2bp08dm', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T09:13:52.792+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T09:13:55.479+0000] {subprocess.py:94} INFO - [0m09:13:55  Running with dbt=1.8.2
[2024-06-20T09:13:56.216+0000] {subprocess.py:94} INFO - [0m09:13:56  Registered adapter: snowflake=1.8.3
[2024-06-20T09:13:57.846+0000] {subprocess.py:94} INFO - [0m09:13:57  Found 20 models, 30 data tests, 11 sources, 682 macros
[2024-06-20T09:13:57.851+0000] {subprocess.py:94} INFO - [0m09:13:57
[2024-06-20T09:14:05.727+0000] {subprocess.py:94} INFO - [0m09:14:05  Concurrency: 1 threads (target='dev')
[2024-06-20T09:14:05.729+0000] {subprocess.py:94} INFO - [0m09:14:05
[2024-06-20T09:14:05.745+0000] {subprocess.py:94} INFO - [0m09:14:05  1 of 1 START sql table model dwh.fact_orders ................................... [RUN]
[2024-06-20T09:14:09.011+0000] {subprocess.py:94} INFO - [0m09:14:09  1 of 1 OK created sql table model dwh.fact_orders .............................. [[32mSUCCESS 1[0m in 3.26s]
[2024-06-20T09:14:09.017+0000] {subprocess.py:94} INFO - [0m09:14:09
[2024-06-20T09:14:09.018+0000] {subprocess.py:94} INFO - [0m09:14:09  Finished running 1 table model in 0 hours 0 minutes and 11.17 seconds (11.17s).
[2024-06-20T09:14:09.178+0000] {subprocess.py:94} INFO - [0m09:14:09
[2024-06-20T09:14:09.179+0000] {subprocess.py:94} INFO - [0m09:14:09  [32mCompleted successfully[0m
[2024-06-20T09:14:09.180+0000] {subprocess.py:94} INFO - [0m09:14:09
[2024-06-20T09:14:09.182+0000] {subprocess.py:94} INFO - [0m09:14:09  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T09:14:10.962+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T09:14:10.963+0000] {local.py:254} INFO - [0m09:14:09  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T09:14:10.990+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T09:14:10.991+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T09:14:10.999+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.dwh.dim_employees', extra=None), Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_orders', extra=None)]
[2024-06-20T09:14:10.999+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.dwh.fact_orders', extra=None)]
[2024-06-20T09:14:11.000+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T09:14:11.239+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-06-20T09:14:11.311+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T09:14:11.374+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.fact_orders.run, run_id=manual__2024-06-20T09:10:32.865792+00:00, execution_date=20240620T091032, start_date=20240620T091347, end_date=20240620T091411
[2024-06-20T09:14:11.446+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T09:14:11.528+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-20T09:14:11.531+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
