[2024-06-20T07:44:05.408+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T07:44:05.484+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T07:39:50.213563+00:00 [queued]>
[2024-06-20T07:44:05.517+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T07:39:50.213563+00:00 [queued]>
[2024-06-20T07:44:05.519+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T07:44:05.594+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtRunLocalOperator): transform.fact_orders.run> on 2024-06-20 07:39:50.213563+00:00
[2024-06-20T07:44:05.612+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.fact_orders.run', 'manual__2024-06-20T07:39:50.213563+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmplt2b_8_s']
[2024-06-20T07:44:05.621+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1823) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T07:44:05.622+0000] {standard_task_runner.py:91} INFO - Job 210: Subtask transform.fact_orders.run
[2024-06-20T07:44:05.623+0000] {standard_task_runner.py:63} INFO - Started process 1827 to run task
[2024-06-20T07:44:05.662+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T07:44:05.743+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.fact_orders.run manual__2024-06-20T07:39:50.213563+00:00 [running]> on host airflow-scheduler
[2024-06-20T07:44:05.960+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.fact_orders.run' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T07:39:50.213563+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T07:39:50.213563+00:00'
[2024-06-20T07:44:05.963+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T07:44:05.987+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T07:44:05.990+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmpqcetk2wm from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T07:44:06.004+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T07:44:06.051+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T07:44:06.052+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T07:44:06.055+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T07:44:06.061+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmp_9qg7pyq/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T07:44:06.063+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpqcetk2wm', '--profiles-dir', '/tmp/tmp_9qg7pyq', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpqcetk2wm
[2024-06-20T07:44:06.065+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T07:44:06.067+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmpqcetk2wm', '--profiles-dir', '/tmp/tmp_9qg7pyq', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T07:44:06.087+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T07:44:11.466+0000] {subprocess.py:94} INFO - [0m07:44:11  Running with dbt=1.8.2
[2024-06-20T07:44:11.974+0000] {subprocess.py:94} INFO - [0m07:44:11  Updating lock file in file path: /tmp/tmpqcetk2wm/package-lock.yml
[2024-06-20T07:44:11.994+0000] {subprocess.py:94} INFO - [0m07:44:11  Installing dbt-labs/dbt_utils
[2024-06-20T07:44:12.659+0000] {subprocess.py:94} INFO - [0m07:44:12  Installed from version 0.8.6
[2024-06-20T07:44:12.662+0000] {subprocess.py:94} INFO - [0m07:44:12  Updated version available: 1.2.0
[2024-06-20T07:44:12.666+0000] {subprocess.py:94} INFO - [0m07:44:12
[2024-06-20T07:44:12.668+0000] {subprocess.py:94} INFO - [0m07:44:12  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T07:44:12.670+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T07:44:14.364+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T07:44:14.367+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T07:44:14.371+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmpqcetk2wm', '--profiles-dir', '/tmp/tmp_9qg7pyq', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmpqcetk2wm
[2024-06-20T07:44:14.373+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T07:44:14.375+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'run', '--models', 'fact_orders', '--project-dir', '/tmp/tmpqcetk2wm', '--profiles-dir', '/tmp/tmp_9qg7pyq', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T07:44:14.399+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T07:44:20.138+0000] {subprocess.py:94} INFO - [0m07:44:20  Running with dbt=1.8.2
[2024-06-20T07:44:21.347+0000] {subprocess.py:94} INFO - [0m07:44:21  Registered adapter: snowflake=1.8.3
[2024-06-20T07:44:24.490+0000] {subprocess.py:94} INFO - [0m07:44:24  Found 20 models, 32 data tests, 11 sources, 682 macros
[2024-06-20T07:44:24.507+0000] {subprocess.py:94} INFO - [0m07:44:24
[2024-06-20T07:44:33.570+0000] {subprocess.py:94} INFO - [0m07:44:33  Concurrency: 1 threads (target='dev')
[2024-06-20T07:44:33.572+0000] {subprocess.py:94} INFO - [0m07:44:33
[2024-06-20T07:44:33.616+0000] {subprocess.py:94} INFO - [0m07:44:33  1 of 1 START sql table model dwh.fact_orders ................................... [RUN]
[2024-06-20T07:44:36.239+0000] {subprocess.py:94} INFO - [0m07:44:36  1 of 1 OK created sql table model dwh.fact_orders .............................. [[32mSUCCESS 1[0m in 2.62s]
[2024-06-20T07:44:36.250+0000] {subprocess.py:94} INFO - [0m07:44:36
[2024-06-20T07:44:36.252+0000] {subprocess.py:94} INFO - [0m07:44:36  Finished running 1 table model in 0 hours 0 minutes and 11.74 seconds (11.74s).
[2024-06-20T07:44:36.494+0000] {subprocess.py:94} INFO - [0m07:44:36
[2024-06-20T07:44:36.497+0000] {subprocess.py:94} INFO - [0m07:44:36  [32mCompleted successfully[0m
[2024-06-20T07:44:36.501+0000] {subprocess.py:94} INFO - [0m07:44:36
[2024-06-20T07:44:36.503+0000] {subprocess.py:94} INFO - [0m07:44:36  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T07:44:38.590+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T07:44:38.593+0000] {local.py:254} INFO - [0m07:44:36  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T07:44:38.684+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T07:44:38.687+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T07:44:38.718+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.dwh.dim_employees', extra=None), Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_orders', extra=None)]
[2024-06-20T07:44:38.721+0000] {local.py:350} INFO - Outlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.dwh.fact_orders', extra=None)]
[2024-06-20T07:44:38.735+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T07:44:39.349+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to None, run_after=None
[2024-06-20T07:44:39.490+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T07:44:39.641+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.fact_orders.run, run_id=manual__2024-06-20T07:39:50.213563+00:00, execution_date=20240620T073950, start_date=20240620T074405, end_date=20240620T074439
[2024-06-20T07:44:39.743+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T07:44:39.861+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-20T07:44:39.874+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
