[2024-06-20T14:31:35.724+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-20T14:31:35.849+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.test manual__2024-06-20T14:29:01.398557+00:00 [queued]>
[2024-06-20T14:31:35.927+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ELT-PROJECT.transform.raw_orders.test manual__2024-06-20T14:29:01.398557+00:00 [queued]>
[2024-06-20T14:31:35.928+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-20T14:31:36.069+0000] {taskinstance.py:2330} INFO - Executing <Task(DbtTestLocalOperator): transform.raw_orders.test> on 2024-06-20 14:29:01.398557+00:00
[2024-06-20T14:31:36.099+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'ELT-PROJECT', 'transform.raw_orders.test', 'manual__2024-06-20T14:29:01.398557+00:00', '--job-id', '641', '--raw', '--subdir', 'DAGS_FOLDER/elt.py', '--cfg-path', '/tmp/tmpo4bg1u5g']
[2024-06-20T14:31:36.106+0000] {standard_task_runner.py:91} INFO - Job 641: Subtask transform.raw_orders.test
[2024-06-20T14:31:36.119+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=4570) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-06-20T14:31:36.122+0000] {standard_task_runner.py:63} INFO - Started process 4582 to run task
[2024-06-20T14:31:36.165+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-06-20T14:31:36.375+0000] {task_command.py:426} INFO - Running <TaskInstance: ELT-PROJECT.transform.raw_orders.test manual__2024-06-20T14:29:01.398557+00:00 [running]> on host airflow-scheduler
[2024-06-20T14:31:37.023+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Data-Ninja' AIRFLOW_CTX_DAG_ID='ELT-PROJECT' AIRFLOW_CTX_TASK_ID='transform.raw_orders.test' AIRFLOW_CTX_EXECUTION_DATE='2024-06-20T14:29:01.398557+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-20T14:29:01.398557+00:00'
[2024-06-20T14:31:37.028+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-20T14:31:37.038+0000] {local.py:174} INFO - Could not import dbtRunner. Falling back to subprocess for invoking dbt.
[2024-06-20T14:31:37.041+0000] {local.py:292} INFO - Cloning project to writable temp directory /tmp/tmp9p0jqis0 from /opt/airflow/dags/dbt/dbt_project
[2024-06-20T14:31:37.062+0000] {local.py:303} INFO - Partial parse is enabled and the latest partial parse file is /tmp/cosmos/ELT-PROJECT__transform/target/partial_parse.msgpack
[2024-06-20T14:31:37.211+0000] {base.py:84} INFO - Using connection ID 'snow_conn' for task execution.
[2024-06-20T14:31:37.225+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2024-06-20T14:31:37.228+0000] {base.py:225} INFO - Using real values for profile dbt_project
[2024-06-20T14:31:37.234+0000] {config.py:291} INFO - Creating temporary profiles.yml with use_mock_values=False at /tmp/tmp5w7kgxhr/profiles.yml with the following contents:
dbt_project:
    outputs:
        dev:
            account: sk84886.europe-west2.gcp
            database: ELT_PROJECT
            password: '{{ env_var(''COSMOS_CONN_SNOWFLAKE_PASSWORD'') }}'
            role: SYSADMIN
            schema: PUBLIC
            type: snowflake
            user: DATANINJA
            warehouse: TRANSFORM
    target: dev

[2024-06-20T14:31:37.247+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp9p0jqis0', '--profiles-dir', '/tmp/tmp5w7kgxhr', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp9p0jqis0
[2024-06-20T14:31:37.263+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T14:31:37.267+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'deps', '--project-dir', '/tmp/tmp9p0jqis0', '--profiles-dir', '/tmp/tmp5w7kgxhr', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T14:31:37.315+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T14:31:48.048+0000] {subprocess.py:94} INFO - [0m14:31:48  Running with dbt=1.8.2
[2024-06-20T14:31:49.533+0000] {subprocess.py:94} INFO - [0m14:31:49  Updating lock file in file path: /tmp/tmp9p0jqis0/package-lock.yml
[2024-06-20T14:31:49.603+0000] {subprocess.py:94} INFO - [0m14:31:49  Installing dbt-labs/dbt_utils
[2024-06-20T14:31:51.764+0000] {subprocess.py:94} INFO - [0m14:31:51  Installed from version 0.8.6
[2024-06-20T14:31:51.769+0000] {subprocess.py:94} INFO - [0m14:31:51  Updated version available: 1.2.0
[2024-06-20T14:31:51.776+0000] {subprocess.py:94} INFO - [0m14:31:51
[2024-06-20T14:31:51.780+0000] {subprocess.py:94} INFO - [0m14:31:51  Updates available for packages: ['dbt-labs/dbt_utils']
[2024-06-20T14:31:51.782+0000] {subprocess.py:94} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T14:31:56.391+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T14:31:56.392+0000] {local.py:254} INFO - Update your versions in packages.yml, then run dbt deps
[2024-06-20T14:31:56.401+0000] {local.py:247} INFO - Trying to run the command:
 ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_orders', '--project-dir', '/tmp/tmp9p0jqis0', '--profiles-dir', '/tmp/tmp5w7kgxhr', '--profile', 'dbt_project', '--target', 'dev']
From /tmp/tmp9p0jqis0
[2024-06-20T14:31:56.403+0000] {subprocess.py:60} INFO - Tmp dir root location: 
 /tmp
[2024-06-20T14:31:56.412+0000] {subprocess.py:73} INFO - Running command: ['/opt/airflow/dbt_venv/bin/dbt', 'test', '--models', 'raw_orders', '--project-dir', '/tmp/tmp9p0jqis0', '--profiles-dir', '/tmp/tmp5w7kgxhr', '--profile', 'dbt_project', '--target', 'dev']
[2024-06-20T14:31:56.492+0000] {subprocess.py:84} INFO - Command output:
[2024-06-20T14:32:11.446+0000] {subprocess.py:94} INFO - [0m14:32:11  Running with dbt=1.8.2
[2024-06-20T14:32:13.813+0000] {subprocess.py:94} INFO - [0m14:32:13  Registered adapter: snowflake=1.8.3
[2024-06-20T14:32:17.673+0000] {subprocess.py:94} INFO - [0m14:32:17  Found 20 models, 27 data tests, 11 sources, 682 macros
[2024-06-20T14:32:17.686+0000] {subprocess.py:94} INFO - [0m14:32:17
[2024-06-20T14:32:25.382+0000] {subprocess.py:94} INFO - [0m14:32:25  Concurrency: 1 threads (target='dev')
[2024-06-20T14:32:25.400+0000] {subprocess.py:94} INFO - [0m14:32:25
[2024-06-20T14:32:25.461+0000] {subprocess.py:94} INFO - [0m14:32:25  1 of 1 START test not_null_raw_orders_ORDERID .................................. [RUN]
[2024-06-20T14:32:28.000+0000] {subprocess.py:94} INFO - [0m14:32:28  1 of 1 PASS not_null_raw_orders_ORDERID ........................................ [[32mPASS[0m in 2.52s]
[2024-06-20T14:32:28.016+0000] {subprocess.py:94} INFO - [0m14:32:28
[2024-06-20T14:32:28.018+0000] {subprocess.py:94} INFO - [0m14:32:28  Finished running 1 test in 0 hours 0 minutes and 10.33 seconds (10.33s).
[2024-06-20T14:32:28.755+0000] {subprocess.py:94} INFO - [0m14:32:28
[2024-06-20T14:32:28.764+0000] {subprocess.py:94} INFO - [0m14:32:28  [32mCompleted successfully[0m
[2024-06-20T14:32:28.767+0000] {subprocess.py:94} INFO - [0m14:32:28
[2024-06-20T14:32:28.777+0000] {subprocess.py:94} INFO - [0m14:32:28  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T14:32:31.719+0000] {subprocess.py:98} INFO - Command exited with return code 0
[2024-06-20T14:32:31.720+0000] {local.py:254} INFO - [0m14:32:28  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
[2024-06-20T14:32:31.847+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/manifest/v12.json is above dbt-ol supported version 7. This might cause errors.
[2024-06-20T14:32:31.848+0000] {local.py:196} WARNING - Artifact schema version: https://schemas.getdbt.com/dbt/run-results/v6.json is above dbt-ol supported version 5. This might cause errors.
[2024-06-20T14:32:31.898+0000] {local.py:349} INFO - Inlets: [Dataset(uri='snowflake://sk84886.europe-west2.gcp/ELT_PROJECT.raw.raw_orders', extra=None)]
[2024-06-20T14:32:31.918+0000] {local.py:350} INFO - Outlets: []
[2024-06-20T14:32:31.924+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-06-20T14:32:33.535+0000] {dag.py:3954} INFO - Setting next_dagrun for ELT-PROJECT to 2024-06-20 00:00:00+00:00, run_after=2024-06-21 00:00:00+00:00
[2024-06-20T14:32:33.840+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-20T14:32:34.078+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=ELT-PROJECT, task_id=transform.raw_orders.test, run_id=manual__2024-06-20T14:29:01.398557+00:00, execution_date=20240620T142901, start_date=20240620T143135, end_date=20240620T143234
[2024-06-20T14:32:34.220+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-20T14:32:34.299+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
